### ISSUE TITLE
Unable to build with current master of Eigen3

### ISSUE THREAD

**Issue by Neumann-A** [SleipnirGroup/Sleipnir#80]
```
E:\all\build\vcpkg_installed\x64-win-llvm-static-md\include\eigen3\Eigen/src/Core/MathFunctions.h(1562,10): error: implicit instantiation of undefined template 'Eigen::numext::signbit_impl<sleipnir::Variable, false, false>'
  return signbit_impl<Scalar>::run(x);
         ^
```

Full build log:
[install-x64-win-llvm-static-md-dbg-out.log](https://github.com/SleipnirGroup/Sleipnir/files/10714702/install-x64-win-llvm-static-md-dbg-out.log)

**Comment by calcmogul** [comment]
Eigen probably made some breaking API changes since the 3.4.0 release. I've reproduced the issue locally on Linux.

**Comment by calcmogul** [comment]
After running a `git bisect` on Eigen, this is the commit that introduced the compilation failure:
```
76a669fb45d68eaf17016c2f93bf0f20a5a880a4 is the first bad commit
commit 76a669fb45d68eaf17016c2f93bf0f20a5a880a4
Author: Charles Schlosser <charless@vt.edu>
Date:   Tue Aug 16 21:32:36 2022 +0000

    add fixed power unary operation

 Eigen/src/Core/GlobalFunctions.h                   |  32 +--
 .../Core/arch/Default/GenericPacketMathFunctions.h | 219 +++++++++++++++++++++
 Eigen/src/Core/functors/UnaryFunctors.h            |  64 ++++++
 Eigen/src/Core/util/ForwardDeclarations.h          |   2 +
 Eigen/src/plugins/ArrayCwiseBinaryOps.h            |  20 --
 Eigen/src/plugins/ArrayCwiseUnaryOps.h             |  29 +++
 Eigen/src/plugins/MatrixCwiseUnaryOps.h            |  10 +
 test/array_cwise.cpp                               |  44 +++++
 unsupported/Eigen/CXX11/src/Tensor/TensorBase.h    |  10 +-
 9 files changed, 391 insertions(+), 39 deletions(-)
```

**Comment by Neumann-A** [comment]
Hm  looks like 
https://github.com/SleipnirGroup/Sleipnir/blob/main/include/sleipnir/autodiff/Variable.hpp
should declare operators `==`, `&` and `|`

**Comment by calcmogul** [comment]
The Variable equality operator can't be implemented to return bool because it's already implemented in https://github.com/SleipnirGroup/Sleipnir/blob/main/include/sleipnir/optimization/Constraints.hpp#L29 to return an equality constraint type. We can't provide both because operators can't be overloaded on return types alone.

**Comment by calcmogul** [comment]
We could work around the issue by not using the coeffiicent-wise operators in the test.

**Comment by Neumann-A** [comment]
> We can't provide both equality operators because operators can't be overloaded on return types alone; the compiler will throw an error on ambiguous overloads.

can `EqualityConstraints` be implicitly converted to `bool` ?

**Comment by calcmogul** [comment]
I think so.

**Comment by calcmogul** [comment]
Since Variable acts like a floating point type, it doesn't seem like &, |, and ~ should be necessary. &, |, and ~ aren't valid for doubles.

Doing what https://www.eigen.tuxfamily.org/dox-3.2/TopicCustomizingEigen.html suggests fails with a static assertion that Variable isn't trivially copyable.
